CREATE TABLE [dbo].[ADDRESS] (
    [ADDRESS_ID]       INT          IDENTITY (1, 1) NOT NULL,
    [ADDRESS_STREET]   VARCHAR (25) NOT NULL,
    [ADDRESS_STREETNO] VARCHAR (25) NOT NULL,
    [ADDRESS_CITY]     VARCHAR (25) NOT NULL,
    [ADDRESS_COUNTRY]  VARCHAR (25) NOT NULL,
    [USER_PROFILE_ID]       INT          NOT NULL,
    CONSTRAINT [PK__Address__498C6686D780CD2A] PRIMARY KEY CLUSTERED ([ADDRESS_ID] ASC),
    CONSTRAINT [FK__ADDRESS__USER_ID__3D5E1FD2] FOREIGN KEY ([USER_PROFILE_ID]) REFERENCES [dbo].[USER_PROFILE] ([USRPROF_ID]) ON DELETE CASCADE
);

