CREATE TABLE [dbo].[MATCH] (
    [MATCH_ID] INT  NOT NULL PRIMARY KEY identity(1, 1),
    [USER_PROFILE_ID] INT NOT NULL,
    [MATCH_USER_PROFILE_ID]    INT NOT NULL,
    [MATCH_DATE] DATETIME NOT NULL, 
    FOREIGN KEY ([USER_PROFILE_ID]) REFERENCES [dbo].[USER_PROFILE] ([USRPROF_ID]),
    FOREIGN KEY ([MATCH_USER_PROFILE_ID]) REFERENCES [dbo].[USER_PROFILE] ([USRPROF_ID]) 
);

