CREATE TABLE [dbo].[USERS] (
    [USER_ID]           INT          IDENTITY (1, 1) NOT NULL,
    [USER_USERNAME]     VARCHAR (25) NOT NULL,
    [USER_EMAIL]        VARCHAR (25) NOT NULL,
    [USER_PASSWORD]     VARCHAR (25) NOT NULL,
    [USER_CREATED_AT]   DATETIME         NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_ID] ASC)
);

