CREATE TABLE [dbo].[USER_PROFILE] (
    [USRPROF_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [USRPROF_NAME]        VARCHAR (25)  NOT NULL,
    [USRPROF_SURNAME]     VARCHAR (25)  NOT NULL,
    [USRPROF_PHONE]       VARCHAR (25)  NOT NULL,
    [USRPROF_DESCRIPTION] VARCHAR (255) NULL,
    [USRPROF_JOB]         VARCHAR (50)  NULL,
    [USRPROF_BIRTHDAY]    DATE          NOT NULL,
    [RELIGION_ID]    INT NOT NULL,
    [STATUS_ID]      INT NOT NULL,
    [ORIENTATION_ID] INT NOT NULL,
    [GENDER_ID]      INT NOT NULL,
    [USER_AGE]         INT NOT NULL,
    [USER_ID] INT NOT NULL, 
    PRIMARY KEY CLUSTERED ([USRPROF_ID] ASC), 
    CONSTRAINT [FK_USER_PROFILE_ToReligion] FOREIGN KEY ([RELIGION_ID]) REFERENCES [RELIGION]([RELIGION_ID]),
    CONSTRAINT [FK_USER_PROFILE_ToGender] FOREIGN KEY ([GENDER_ID]) REFERENCES [GENDER]([GENDER_ID]),
    CONSTRAINT [FK_USER_PROFILE_ToStatus] FOREIGN KEY ([STATUS_ID]) REFERENCES [MARITAL_STATUS]([MRTSTS_ID]),
    CONSTRAINT [FK_USER_PROFILE_ToOrientation] FOREIGN KEY ([ORIENTATION_ID]) REFERENCES [ORIENTATION]([ORIENT_ID]),
    CONSTRAINT [FK_USER_PROFILE_ToProfile] FOREIGN KEY ([USER_ID]) REFERENCES [USERS]([USER_ID]) ON DELETE CASCADE
);

